#### Making the prompts for LLM training

In [30]:
%pip install shap

Requirement already satisfied: shap in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (0.46.0)
Requirement already satisfied: numpy in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from shap) (1.26.4)
Requirement already satisfied: scipy in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from shap) (1.11.4)
Requirement already satisfied: scikit-learn in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from shap) (1.3.2)
Requirement already satisfied: pandas in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from shap) (2.1.4)
Requirement already satisfied: tqdm>=4.27.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from shap) (4.66.5)
Requirement already satisfied: packaging>20.9 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from shap) (23.2)
Requirement already satisfied: slicer==0.0.8 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from shap) (0.0.8)
Requirement already satisfied: numba in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from shap) (0.60.0)
Requirement already satisfied: cloudpickle in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from shap) (3.1.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from numba->shap) (0.43.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pandas->shap) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pandas->shap) (2024.1)
Requirement already satisfied: joblib>=1.1.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from scikit-learn->shap) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from scikit-learn->shap) (3.5.0)
Requirement already satisfied: six>=1.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->shap) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
import shap
import numpy as np
from xgboost import XGBClassifier

In [8]:
data=pd.read_csv("/teamspace/studios/this_studio/NLP-Projects/LLM-for-IDS-log-analysis/Data/Classifier_Data/bot_iot_dataset_preprocessed.csv")
data.head()

,stime,flgs_e,flgs_e s,flgs_e dS,flgs_e g,flgs_e *,flgs_eU,flgs_e &,flgs_e d,flgs_e F,...,tnp_per_dport,ar_p_proto_p_srcip,ar_p_proto_p_dstip,n_in_conn_p_srcip,n_in_conn_p_dstip,ar_p_proto_p_sport,ar_p_proto_p_dport,pkts_p_state_p_protocol_p_destip,pkts_p_state_p_protocol_p_srcip,attack_type
0,1.526963e+09,1,0,0,0,0,0,0,0,0,...,8,4918.426175,939.965691,641.0,5208,564.567137,10430.133552,6482,23345,3
1,1.528081e+09,0,1,0,0,0,0,0,0,0,...,13108094,3908.819243,1254.250649,120.0,6669,0.094425,100.862697,12994,15429,1
2,1.526982e+09,1,0,0,0,0,0,0,0,0,...,21,3908.819243,1254.250649,120.0,6669,4368.510051,18097.726590,13229,23301,3
3,1.528081e+09,0,1,0,0,0,0,0,0,0,...,13108094,4574.700595,9901.705447,146.0,5063,0.191534,100.862697,14111,30428,1
4,1.526982e+09,1,0,0,0,0,0,0,0,0,...,23,4918.426175,1254.250649,641.0,6669,1856.201331,5937.703676,13229,23345,3

In [18]:
features=['flgs_e', 'flgs_e s', 'flgs_e dS', 'flgs_e g', 'flgs_e *', 'flgs_eU',
       'flgs_e &', 'flgs_e    F', 'flgs_e r', 'proto_tcp', 'proto_udp',
       'proto_icmp', 'proto_arp', 'proto_ipv6-icmp', 'proto_rarp',
       'proto_igmp', 'saddr_192.168.100.149', 'saddr_192.168.100.148',
       'saddr_192.168.100.150', 'saddr_192.168.100.147', 'saddr_192.168.100.3',
       'saddr_192.168.100.7', 'saddr_192.168.100.5', 'saddr_192.168.100.4',
       'saddr_192.168.100.1', 'daddr_192.168.100.149', 'daddr_192.168.100.150',
       'daddr_192.168.100.147', 'daddr_192.168.100.3', 'daddr_192.168.100.7',
       'daddr_192.168.100.6', 'daddr_192.168.100.5', 'daddr_192.168.100.4',
       'daddr_private', 'daddr_external', 'pkts', 'bytes', 'state_RST',
       'state_CON', 'state_NRS', 'state_ACC', 'state_MAS', 'dur', 'mean',
       'min', 'dpkts', 'dbytes', 'tnp_per_dport', 'ar_p_proto_p_dstip',
       'ar_p_proto_p_sport', 'pkts_p_state_p_protocol_p_destip','attack_type']

In [17]:
len(data)*0.061

3008.398

In [20]:
data_sample=data.sample(frac=0.061).reset_index()
data_sample=data_sample[features].iloc[:3000]
data_sample.head()

,flgs_e,flgs_e s,flgs_e dS,flgs_e g,flgs_e *,flgs_eU,flgs_e &,flgs_e F,flgs_e r,proto_tcp,...,dur,mean,min,dpkts,dbytes,tnp_per_dport,ar_p_proto_p_dstip,ar_p_proto_p_sport,pkts_p_state_p_protocol_p_destip,attack_type
0,1,0,0,0,0,0,0,0,0,1,...,0.036125,0.036125,0.036125,1,60,2,5274.167447,33.222485,65132,4
1,1,0,0,0,0,0,0,0,0,1,...,8.813676,0.001685,0.000000,1,60,13108094,5274.167447,0.340380,65132,2
2,1,0,0,0,0,0,0,0,0,1,...,33.937874,0.000020,0.000000,4,766,13108094,5274.167447,0.265190,65132,1
3,0,0,0,1,0,0,0,0,0,1,...,23.880112,0.093670,0.043778,2,120,13108094,5274.167447,0.169986,65132,1
4,1,0,0,0,0,0,0,0,0,0,...,5.047973,0.000000,0.000000,0,0,14770,0.201614,0.198099,5006,0

In [75]:
metadata={'pkseqid': 'Row Identifier',
 'stime': 'Record start time',
 'flgs_e': 'State ESTABLISHED',
 'flgs_e s' : 'State ESTABLISHED and State SYN_SENT',
 'flgs_e dS' : 'State ESTABLISHED and State SYN_RECEIVED',
 'flgs_e g' : 'State ESTABLISHED and State FIN_WAIT_1',
 'flgs_e *' : 'State ESTABLISHED and State ACK',
 'flgs_eU' : 'State ESTABLISHED and State URGENT',
 'flgs_e &' : 'State ESTABLISHED and State PUSH',
 'flgs_e    F' : 'State ESTABLISHED and State FIN_WAIT_2',
 'flgs_e r' : 'State ESTABLISHED and State RESET',
 'proto_tcp': 'TCP',
 'proto_udp': 'UDP',
 'proto_icmp': 'ICMP',
 'proto_arp': 'ARP',
 'proto_ipv6-icmp': 'IPV6-ICMP',
 'proto_rarp': 'RARP',
 'proto_igmp': 'IGMP',
 'saddr_192.168.100.149': '192.168.100.149',
 'saddr_192.168.100.148': '192.168.100.148',
 'saddr_192.168.100.150': '192.168.100.150',
 'saddr_192.168.100.147': '192.168.100.147',
 'saddr_192.168.100.1': '192.168.100.1',
 'saddr_192.168.100.3': '192.168.100.3',
 'saddr_192.168.100.4': '192.168.100.4',
 'saddr_192.168.100.7': '192.168.100.7',
 'saddr_192.168.100.5': '192.168.100.5',
 'daddr_192.168.100.149': '192.168.100.149',
 'daddr_192.168.100.148': '192.168.100.148',
 'daddr_192.168.100.150': '192.168.100.150',
 'daddr_192.168.100.147': '192.168.100.147',
 'daddr_192.168.100.1': '192.168.100.1',
 'daddr_192.168.100.3': '192.168.100.3',
 'daddr_192.168.100.4': '192.168.100.4',
 'daddr_192.168.100.7': '192.168.100.7',
 'daddr_192.168.100.6': '192.168.100.6',
 'daddr_192.168.100.5': '192.168.100.5',
 'daddr_private' : 'Private',
 'daddr_external' : 'External',
 'pkts': 'Total count of packets in transaction',
 'bytes': 'Total number of bytes in transaction',
 'state': 'Transaction state',
 'state_RST' : 'RESET',
 'state_CON' : 'CONNECTED',
 'state_NRS' : 'NO_RESPONSE',
 'state_ACC' : 'ACCEPTED',
 'state_MAS' : 'MASQUERADE',
 'ltime': 'Record last time',
 'seq': 'Argus sequence number',
 'dur': 'Record total duration',
 'mean': 'Average duration of aggregated records',
 'stddev': 'Standard deviation of aggregated records',
 'sum': 'Total duration of aggregated records',
 'min': 'Minimum duration of aggregated records',
 'max': 'Maximum duration of aggregated records',
 'spkts': 'Source-to-destination packet count',
 'dpkts': 'Destination-to-source packet count',
 'sbytes': 'Source-to-destination byte count',
 'dbytes': 'Destination-to-source byte count',
 'rate': 'Total packets per second in transaction',
 'srate': 'Source-to-destination packets per second',
 'drate': 'Destination-to-source packets per second',
 'tnbpsrcip': 'Total Number of bytes per source IP',
 'tnbpdstip': 'Total Number of bytes per Destination IP',
 'tnp_psrcip': 'Total Number of packets per source IP',
 'tnp_pdstip': 'Total Number of packets per Destination IP',
 'tnp_perproto': 'Total Number of packets per protocol',
 'tnp_per_dport': 'Total Number of packets per destination port',
 'ar_p_proto_p_srcip': 'Average rate per protocol per Source IP',
 'ar_p_proto_p_dstip': 'Average rate per protocol per Destination IP',
 'n_in_conn_p_srcip': 'Number of inbound connections per source IP',
 'n_in_conn_p_dstip': 'Number of inbound connections per destination IP',
 'ar_p_proto_p_sport': 'Average rate per protocol per source port',
 'ar_p_proto_p_dport': 'Average rate per protocol per destination port',
 'pkts_p_state_p_protocol_p_destip': 'Number of packets grouped by state of flows and protocols per destination IP',
 'pkts_p_state_p_protocol_p_srcip': 'Number of packets grouped by state of flows and protocols per source IP',
 'attack': 'Class label: 0 for Normal traffic, 1 for Attack Traffic',
 'category': 'Traffic category',
 'subcategory ': 'Traffic subcategory', 
 'attack_type' : 'Numeric representation of Traffic category and subcategory (0 for Normal, 1 for DoS, 2 for DDoS, 3 for OS_Fingerprint, 4 for Service_Scan, 5 for Keylogging, 6 for Data_Exfiltration)'
  }

In [32]:
features=['flgs_e', 'flgs_e s', 'flgs_e dS', 'flgs_e g', 'flgs_e *', 'flgs_eU',
       'flgs_e &', 'flgs_e    F', 'flgs_e r', 'proto_tcp', 'proto_udp',
       'proto_icmp', 'proto_arp', 'proto_ipv6-icmp', 'proto_rarp',
       'proto_igmp', 'saddr_192.168.100.149', 'saddr_192.168.100.148',
       'saddr_192.168.100.150', 'saddr_192.168.100.147', 'saddr_192.168.100.3',
       'saddr_192.168.100.7', 'saddr_192.168.100.5', 'saddr_192.168.100.4',
       'saddr_192.168.100.1', 'daddr_192.168.100.149', 'daddr_192.168.100.150',
       'daddr_192.168.100.147', 'daddr_192.168.100.3', 'daddr_192.168.100.7',
       'daddr_192.168.100.6', 'daddr_192.168.100.5', 'daddr_192.168.100.4',
       'daddr_private', 'daddr_external', 'pkts', 'bytes', 'state_RST',
       'state_CON', 'state_NRS', 'state_ACC', 'state_MAS', 'dur', 'mean',
       'min', 'dpkts', 'dbytes', 'tnp_per_dport', 'ar_p_proto_p_dstip',
       'ar_p_proto_p_sport', 'pkts_p_state_p_protocol_p_destip']

In [33]:
X_train=data.sample(frac=0.6)
X_test=data.sample(frac=0.4)
y_train=X_train["attack_type"]
y_test=X_test["attack_type"]
X_train.drop("attack_type",axis=1,inplace=True)
X_test.drop("attack_type",axis=1,inplace=True)
X_train=X_train[features]
X_test=X_test[features]

In [34]:
model=XGBClassifier()
model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [35]:
model.score(X_test,y_test)

0.9883915445835657

In [90]:
explainer=shap.TreeExplainer(model)
shap_values=explainer.shap_values(data_sample.drop("attack_type",axis=1))

In [ ]:
#prompt example : Network Traffic (features), Classifier Decision: Attack, SHAP Values: Feature A (+0.3), Feature B (-0.2), Feature C (+0.1)

In [71]:
def get_key(dict,value) :
    return [key for key in dict.keys() if dict[key]==value][0]
def sort_get_best(shap_values,features) :
    feat_dict={features[i]:shap_values[i] for i in range(0,len(features))}
    sorted_shap = np.argsort(np.abs(shap_values))
    result_shap = shap_values[sorted_shap][::-1][:10]
    feature_importances={get_key(feat_dict,value):value for value in result_shap}
    return feature_importances

In [89]:
y_preds=model.predict(data_sample.drop("attack_type",axis=1))

In [56]:
classes={0:'Normal Traffic',1 : 'DoS attack',2: 'DDoS attack',3: 'OS Fingerprint attack',4: 'Service Scan attack',5 : 'Keylogging attack',6 : 'Data Exfiltration attack'}

In [62]:
data_sample.columns

Index(['flgs_e', 'flgs_e s', 'flgs_e dS', 'flgs_e g', 'flgs_e *', 'flgs_eU',
       'flgs_e &', 'flgs_e    F', 'flgs_e r', 'proto_tcp', 'proto_udp',
       'proto_icmp', 'proto_arp', 'proto_ipv6-icmp', 'proto_rarp',
       'proto_igmp', 'saddr_192.168.100.149', 'saddr_192.168.100.148',
       'saddr_192.168.100.150', 'saddr_192.168.100.147', 'saddr_192.168.100.3',
       'saddr_192.168.100.7', 'saddr_192.168.100.5', 'saddr_192.168.100.4',
       'saddr_192.168.100.1', 'daddr_192.168.100.149', 'daddr_192.168.100.150',
       'daddr_192.168.100.147', 'daddr_192.168.100.3', 'daddr_192.168.100.7',
       'daddr_192.168.100.6', 'daddr_192.168.100.5', 'daddr_192.168.100.4',
       'daddr_private', 'daddr_external', 'pkts', 'bytes', 'state_RST',
       'state_CON', 'state_NRS', 'state_ACC', 'state_MAS', 'dur', 'mean',
       'min', 'dpkts', 'dbytes', 'tnp_per_dport', 'ar_p_proto_p_dstip',
       'ar_p_proto_p_sport', 'pkts_p_state_p_protocol_p_destip',
       'attack_type'],
      dtype='object')

In [84]:
data_6=data[data["attack_type"]==6][data_sample.columns]
data_5=data[data["attack_type"]==5][data_sample.columns].iloc[:600]
data_sample=pd.concat([data_sample,data_6,data_5],axis=0)

attack_type
5    1548
3     608
0     605
2     602
4     555
1     544
6     125
Name: count, dtype: int64

In [91]:
#making the prompts
flags_state=['flgs_e', 'flgs_e s', 'flgs_e dS', 'flgs_e g', 'flgs_e *', 'flgs_eU',
       'flgs_e &', 'flgs_e    F', 'flgs_e r']
protos=['proto_tcp', 'proto_udp',
       'proto_icmp', 'proto_arp', 'proto_ipv6-icmp', 'proto_rarp',
       'proto_igmp']
s_addr=['saddr_192.168.100.149', 'saddr_192.168.100.148',
       'saddr_192.168.100.150', 'saddr_192.168.100.147', 'saddr_192.168.100.3',
       'saddr_192.168.100.7', 'saddr_192.168.100.5', 'saddr_192.168.100.4',
       'saddr_192.168.100.1']
d_addr=['daddr_192.168.100.149', 'daddr_192.168.100.150',
       'daddr_192.168.100.147', 'daddr_192.168.100.3', 'daddr_192.168.100.7',
       'daddr_192.168.100.6', 'daddr_192.168.100.5', 'daddr_192.168.100.4']
d_type=['daddr_private','daddr_external']
states=['state_RST','state_CON', 'state_NRS', 'state_ACC', 'state_MAS']
transaction_info=['pkts', 'bytes','dur', 'mean',
       'min', 'dpkts', 'dbytes', 'tnp_per_dport', 'ar_p_proto_p_dstip',
       'ar_p_proto_p_sport', 'pkts_p_state_p_protocol_p_destip']
dict_llm={}
for i in range(len(data_sample)) :
    dict_llm[i]={}
    #network traffic and classifier decision
    prompt="Network Traffic :\n\n"
    data_row=data_sample.iloc[i]
    for feature in data_row.index :
        if feature=="attack_type" :
           prompt=prompt+f"\nClassifier Decision : {classes[y_preds[i]]}\n"
        elif feature in flags_state :
            if data_row[feature]==1.0 :
                prompt=prompt+f"Flow state flags: {metadata[feature]}\n"
        elif feature in protos :
            if data_row[feature]==1.0 :
                prompt=prompt+f"Transaction protocol : {metadata[feature]}\n"
        elif feature in s_addr :
            if data_row[feature]==1.0 :
                prompt=prompt+f"Source IP address : {metadata[feature]}\n"
        elif feature in d_addr :
            if data_row[feature]==1.0 :
                prompt=prompt+f"Destination IP address : {metadata[feature]}\n"
        elif feature in d_type :
            if data_row[feature]==1.0 :
                prompt=prompt+f"Destination address type : {metadata[feature]}\n"
        elif feature in states :
            if data_row[feature]==1.0 :
                prompt=prompt+f"-Transaction State : {metadata[feature]}\n"
        elif feature in transaction_info :
            if "\nTransaction information :\n" in prompt :
                prompt=prompt+f"-{metadata[feature]} : {round(data_row[feature],2)}\n"
            else :
                prompt=prompt+"\nTransaction information :\n"
                prompt=prompt+f"-{metadata[feature]} : {round(data_row[feature],2)}\n"
    #shap values
    prompt=prompt+"\nSHAP Values that represent how much a particular feature influenced the final decision:\n"
    best_shap_values=sort_get_best(shap_values[i,:,y_preds[i]],features)
    for feature in best_shap_values.keys() :
        if feature in flags_state :
           prompt=prompt+ f"-SHAP Value for Flow state flags : {metadata[feature]} : {round(best_shap_values[feature],2)} (Feature value: {data_row[feature]})\n"
        elif feature in protos :
           prompt=prompt+ f"-SHAP Value for Transaction protocol : {metadata[feature]} : {round(best_shap_values[feature],2)}. (Feature value: {data_row[feature]})\n"
        elif feature in s_addr :
           prompt=prompt+ f"-SHAP Value for Source IP Address ({metadata[feature]}) : {round(best_shap_values[feature],2)}. (Feature value: {data_row[feature]})\n"
        elif feature in d_addr :
           prompt=prompt+ f"-SHAP Value for Destination IP Address ({metadata[feature]}) : {round(best_shap_values[feature],2)}. (Feature value: {data_row[feature]})\n"
        elif feature in d_type :
           prompt=prompt+ f"-SHAP Value for Destination Address Type ({metadata[feature]}) : {round(best_shap_values[feature],2)}. (Feature value: {data_row[feature]})\n"
        elif feature in states :
           prompt=prompt+ f"-SHAP Value for Transaction state ({metadata[feature]}) : {round(best_shap_values[feature],2)}. (Feature value: {data_row[feature]})\n"
        else :
           prompt=prompt+ f"-SHAP Value for {metadata[feature]} : {round(best_shap_values[feature],2)}. (Feature value: {data_row[feature]})\n"
    dict_llm[i]["prompt"]=prompt[:-1]
    print(f"{i} done.")

0 done.
1 done.
2 done.
3 done.
4 done.
5 done.
6 done.
7 done.
8 done.
9 done.
10 done.
11 done.
12 done.
13 done.
14 done.
15 done.
16 done.
17 done.
18 done.
19 done.
20 done.
21 done.
22 done.
23 done.
24 done.
25 done.
26 done.
27 done.
28 done.
29 done.
30 done.
31 done.
32 done.
33 done.
34 done.
35 done.
36 done.
37 done.
38 done.
39 done.
40 done.
41 done.
42 done.
43 done.
44 done.
45 done.
46 done.
47 done.
48 done.
49 done.
50 done.
51 done.
52 done.
53 done.
54 done.
55 done.
56 done.
57 done.
58 done.
59 done.
60 done.
61 done.
62 done.
63 done.
64 done.
65 done.
66 done.
67 done.
68 done.
69 done.
70 done.
71 done.
72 done.
73 done.
74 done.
75 done.
76 done.
77 done.
78 done.
79 done.
80 done.
81 done.
82 done.
83 done.
84 done.
85 done.
86 done.
87 done.
88 done.
89 done.
90 done.
91 done.
92 done.
93 done.
94 done.
95 done.
96 done.
97 done.
98 done.
99 done.
100 done.
101 done.
102 done.
103 done.
104 done.
105 done.
106 done.
107 done.
108 done.
109 done.
110 done.
111 done.
112 done.
113 done.
114 done.
115 done.
116 done.
117 done.
118 done.
119 done.
120 done.
121 done.
122 done.
123 done.
124 done.
125 done.
126 done.
127 done.
128 done.
129 done.
130 done.
131 done.
132 done.
133 done.
134 done.
135 done.
136 done.
137 done.
138 done.
139 done.
140 done.
141 done.
142 done.
143 done.
144 done.
145 done.
146 done.
147 done.
148 done.
149 done.
150 done.
151 done.
152 done.
153 done.
154 done.
155 done.
156 done.
157 done.
158 done.
159 done.
160 done.
161 done.
162 done.
163 done.
164 done.
165 done.
166 done.
167 done.
168 done.
169 done.
170 done.
171 done.
172 done.
173 done.
174 done.
175 done.
176 done.
177 done.
178 done.
179 done.
180 done.
181 done.
182 done.
183 done.
184 done.
185 done.
186 done.
187 done.
188 done.
189 done.
190 done.
191 done.
192 done.
193 done.
194 done.
195 done.
196 done.
197 done.
198 done.
199 done.
200 done.
201 done.
202 done.
203 done.
204 done.
205 done.
206 done.
207 done.
208 done.
209 done.
210 done.
211 done.
212 done.
213 done.
214 done.
215 done.
216 done.
217 done.
218 done.
219 done.
220 done.
221 done.
222 done.
223 done.
224 done.
225 done.
226 done.
227 done.
228 done.
229 done.
230 done.
231 done.
232 done.
233 done.
234 done.
235 done.
236 done.
237 done.
238 done.
239 done.
240 done.
241 done.
242 done.
243 done.
244 done.
245 done.
246 done.
247 done.
248 done.
249 done.
250 done.
251 done.
252 done.
253 done.
254 done.
255 done.
256 done.
257 done.
258 done.
259 done.
260 done.
261 done.
262 done.
263 done.
264 done.
265 done.
266 done.
267 done.
268 done.
269 done.
270 done.
271 done.
272 done.
273 done.
274 done.
275 done.
276 done.
277 done.
278 done.
279 done.
280 done.
281 done.
282 done.
283 done.
284 done.
285 done.
286 done.
287 done.
288 done.
289 done.
290 done.
291 done.
292 done.
293 done.
294 done.
295 done.
296 done.
297 done.
298 done.
299 done.
300 done.
301 done.
302 done.
303 done.
304 done.
305 done.
306 done.
307 done.
308 done.
309 done.
310 done.
311 done.
312 done.
313 done.
314 done.
315 done.
316 done.
317 done.
318 done.
319 done.
320 done.
321 done.
322 done.
323 done.
324 done.
325 done.
326 done.
327 done.
328 done.
329 done.
330 done.
331 done.
332 done.
333 done.
334 done.
335 done.
336 done.
337 done.
338 done.
339 done.
340 done.
341 done.
342 done.
343 done.
344 done.
345 done.
346 done.
347 done.
348 done.
349 done.
350 done.
351 done.
352 done.
353 done.
354 done.
355 done.
356 done.
357 done.
358 done.
359 done.
360 done.
361 done.
362 done.
363 done.
364 done.
365 done.
366 done.
367 done.
368 done.
369 done.
370 done.
371 done.
372 done.
373 done.
374 done.
375 done.
376 done.
377 done.
378 done.
379 done.
380 done.
381 done.
382 done.
383 done.
384 done.
385 done.
386 done.
387 done.
388 done.
389 done.
390 done.
391 done.
392 done.
393 done.
394 done.
395 done.
396 done.
397 done.
398 done.
399 done.
400 done.
401 done.
402 done.
403 done.
404 done.
405 done.
406 done.
407 done.
408 done.
409 done.
410 done.
411 done.
412 done.
413 done.
414 done.
415 done.
416 done.
417 done.
418 done.
419 done.
420 done.
421 done.
422 done.
423 done.
424 done.
425 done.
426 done.
427 done.
428 done.
429 done.
430 done.
431 done.
432 done.
433 done.
434 done.
435 done.
436 done.
437 done.
438 done.
439 done.
440 done.
441 done.
442 done.
443 done.
444 done.
445 done.
446 done.
447 done.
448 done.
449 done.
450 done.
451 done.
452 done.
453 done.
454 done.
455 done.
456 done.
457 done.
458 done.
459 done.
460 done.
461 done.
462 done.
463 done.
464 done.
465 done.
466 done.
467 done.
468 done.
469 done.
470 done.
471 done.
472 done.
473 done.
474 done.
475 done.
476 done.
477 done.
478 done.
479 done.
480 done.
481 done.
482 done.
483 done.
484 done.
485 done.
486 done.
487 done.
488 done.
489 done.
490 done.
491 done.
492 done.
493 done.
494 done.
495 done.
496 done.
497 done.
498 done.
499 done.
500 done.
501 done.
502 done.
503 done.
504 done.
505 done.
506 done.
507 done.
508 done.
509 done.
510 done.
511 done.
512 done.
513 done.
514 done.
515 done.
516 done.
517 done.
518 done.
519 done.
520 done.
521 done.
522 done.
523 done.
524 done.
525 done.
526 done.
527 done.
528 done.
529 done.
530 done.
531 done.
532 done.
533 done.
534 done.
535 done.
536 done.
537 done.
538 done.
539 done.
540 done.
541 done.
542 done.
543 done.
544 done.
545 done.
546 done.
547 done.
548 done.
549 done.
550 done.
551 done.
552 done.
553 done.
554 done.
555 done.
556 done.
557 done.
558 done.
559 done.
560 done.
561 done.
562 done.
563 done.
564 done.
565 done.
566 done.
567 done.
568 done.
569 done.
570 done.
571 done.
572 done.
573 done.
574 done.
575 done.
576 done.
577 done.
578 done.
579 done.
580 done.
581 done.
582 done.
583 done.
584 done.
585 done.
586 done.
587 done.
588 done.
589 done.
590 done.
591 done.
592 done.
593 done.
594 done.
595 done.
596 done.
597 done.
598 done.
599 done.
600 done.
601 done.
602 done.
603 done.
604 done.
605 done.
606 done.
607 done.
608 done.
609 done.
610 done.
611 done.
612 done.
613 done.
614 done.
615 done.
616 done.
617 done.
618 done.
619 done.
620 done.
621 done.
622 done.
623 done.
624 done.
625 done.
626 done.
627 done.
628 done.
629 done.
630 done.
631 done.
632 done.
633 done.
634 done.
635 done.
636 done.
637 done.
638 done.
639 done.
640 done.
641 done.
642 done.
643 done.
644 done.
645 done.
646 done.
647 done.
648 done.
649 done.
650 done.
651 done.
652 done.
653 done.
654 done.
655 done.
656 done.
657 done.
658 done.
659 done.
660 done.
661 done.
662 done.
663 done.
664 done.
665 done.
666 done.
667 done.
668 done.
669 done.
670 done.
671 done.
672 done.
673 done.
674 done.
675 done.
676 done.
677 done.
678 done.
679 done.
680 done.
681 done.
682 done.
683 done.
684 done.
685 done.
686 done.
687 done.
688 done.
689 done.
690 done.
691 done.
692 done.
693 done.
694 done.
695 done.
696 done.
697 done.
698 done.
699 done.
700 done.
701 done.
702 done.
703 done.
704 done.
705 done.
706 done.
707 done.
708 done.
709 done.
710 done.
711 done.
712 done.
713 done.
714 done.
715 done.
716 done.
717 done.
718 done.
719 done.
720 done.
721 done.
722 done.
723 done.
724 done.
725 done.
726 done.
727 done.
728 done.
729 done.
730 done.
731 done.
732 done.
733 done.
734 done.
735 done.
736 done.
737 done.
738 done.
739 done.
740 done.
741 done.
742 done.
743 done.
744 done.
745 done.
746 done.
747 done.
748 done.
749 done.
750 done.
751 done.
752 done.
753 done.
754 done.
755 done.
756 done.
757 done.
758 done.
759 done.
760 done.
761 done.
762 done.
763 done.
764 done.
765 done.
766 done.
767 done.
768 done.
769 done.
770 done.
771 done.
772 done.
773 done.
774 done.
775 done.
776 done.
777 done.
778 done.
779 done.
780 done.
781 done.
782 done.
783 done.
784 done.
785 done.
786 done.
787 done.
788 done.
789 done.
790 done.
791 done.
792 done.
793 done.
794 done.
795 done.
796 done.
797 done.
798 done.
799 done.
800 done.
801 done.
802 done.
803 done.
804 done.
805 done.
806 done.
807 done.
808 done.
809 done.
810 done.
811 done.
812 done.
813 done.
814 done.
815 done.
816 done.
817 done.
818 done.
819 done.
820 done.
821 done.
822 done.
823 done.
824 done.
825 done.
826 done.
827 done.
828 done.
829 done.
830 done.
831 done.
832 done.
833 done.
834 done.
835 done.
836 done.
837 done.
838 done.
839 done.
840 done.
841 done.
842 done.
843 done.
844 done.
845 done.
846 done.
847 done.
848 done.
849 done.
850 done.
851 done.
852 done.
853 done.
854 done.
855 done.
856 done.
857 done.
858 done.
859 done.
860 done.
861 done.
862 done.
863 done.
864 done.
865 done.
866 done.
867 done.
868 done.
869 done.
870 done.
871 done.
872 done.
873 done.
874 done.
875 done.
876 done.
877 done.
878 done.
879 done.
880 done.
881 done.
882 done.
883 done.
884 done.
885 done.
886 done.
887 done.
888 done.
889 done.
890 done.
891 done.
892 done.
893 done.
894 done.
895 done.
896 done.
897 done.
898 done.
899 done.
900 done.
901 done.
902 done.
903 done.
904 done.
905 done.
906 done.
907 done.
908 done.
909 done.
910 done.
911 done.
912 done.
913 done.
914 done.
915 done.
916 done.
917 done.
918 done.
919 done.
920 done.
921 done.
922 done.
923 done.
924 done.
925 done.
926 done.
927 done.
928 done.
929 done.
930 done.
931 done.
932 done.
933 done.
934 done.
935 done.
936 done.
937 done.
938 done.
939 done.
940 done.
941 done.
942 done.
943 done.
944 done.
945 done.
946 done.
947 done.
948 done.
949 done.
950 done.
951 done.
952 done.
953 done.
954 done.
955 done.
956 done.
957 done.
958 done.
959 done.
960 done.
961 done.
962 done.
963 done.
964 done.
965 done.
966 done.
967 done.
968 done.
969 done.
970 done.
971 done.
972 done.
973 done.
974 done.
975 done.
976 done.
977 done.
978 done.
979 done.
980 done.
981 done.
982 done.
983 done.
984 done.
985 done.
986 done.
987 done.
988 done.
989 done.
990 done.
991 done.
992 done.
993 done.
994 done.
995 done.
996 done.
997 done.
998 done.
999 done.
1000 done.
1001 done.
1002 done.
1003 done.
1004 done.
1005 done.
1006 done.
1007 done.
1008 done.
1009 done.
1010 done.
1011 done.
1012 done.
1013 done.
1014 done.
1015 done.
1016 done.
1017 done.
1018 done.
1019 done.
1020 done.
1021 done.
1022 done.
1023 done.
1024 done.
1025 done.
1026 done.
1027 done.
1028 done.
1029 done.
1030 done.
1031 done.
1032 done.
1033 done.
1034 done.
1035 done.
1036 done.
1037 done.
1038 done.
1039 done.
1040 done.
1041 done.
1042 done.
1043 done.
1044 done.
1045 done.
1046 done.
1047 done.
1048 done.
1049 done.
1050 done.
1051 done.
1052 done.
1053 done.
1054 done.
1055 done.
1056 done.
1057 done.
1058 done.
1059 done.
1060 done.
1061 done.
1062 done.
1063 done.
1064 done.
1065 done.
1066 done.
1067 done.
1068 done.
1069 done.
1070 done.
1071 done.
1072 done.
1073 done.
1074 done.
1075 done.
1076 done.
1077 done.
1078 done.
1079 done.
1080 done.
1081 done.
1082 done.
1083 done.
1084 done.
1085 done.
1086 done.
1087 done.
1088 done.
1089 done.
1090 done.
1091 done.
1092 done.
1093 done.
1094 done.
1095 done.
1096 done.
1097 done.
1098 done.
1099 done.
1100 done.
1101 done.
1102 done.
1103 done.
1104 done.
1105 done.
1106 done.
1107 done.
1108 done.
1109 done.
1110 done.
1111 done.
1112 done.
1113 done.
1114 done.
1115 done.
1116 done.
1117 done.
1118 done.
1119 done.
1120 done.
1121 done.
1122 done.
1123 done.
1124 done.
1125 done.
1126 done.
1127 done.
1128 done.
1129 done.
1130 done.
1131 done.
1132 done.
1133 done.
1134 done.
1135 done.
1136 done.
1137 done.
1138 done.
1139 done.
1140 done.
1141 done.
1142 done.
1143 done.
1144 done.
1145 done.
1146 done.
1147 done.
1148 done.
1149 done.
1150 done.
1151 done.
1152 done.
1153 done.
1154 done.
1155 done.
1156 done.
1157 done.
1158 done.
1159 done.
1160 done.
1161 done.
1162 done.
1163 done.
1164 done.
1165 done.
1166 done.
1167 done.
1168 done.
1169 done.
1170 done.
1171 done.
1172 done.
1173 done.
1174 done.
1175 done.
1176 done.
1177 done.
1178 done.
1179 done.
1180 done.
1181 done.
1182 done.
1183 done.
1184 done.
1185 done.
1186 done.
1187 done.
1188 done.
1189 done.
1190 done.
1191 done.
1192 done.
1193 done.
1194 done.
1195 done.
1196 done.
1197 done.
1198 done.
1199 done.
1200 done.
1201 done.
1202 done.
1203 done.
1204 done.
1205 done.
1206 done.
1207 done.
1208 done.
1209 done.
1210 done.
1211 done.
1212 done.
1213 done.
1214 done.
1215 done.
1216 done.
1217 done.
1218 done.
1219 done.
1220 done.
1221 done.
1222 done.
1223 done.
1224 done.
1225 done.
1226 done.
1227 done.
1228 done.
1229 done.
1230 done.
1231 done.
1232 done.
1233 done.
1234 done.
1235 done.
1236 done.
1237 done.
1238 done.
1239 done.
1240 done.
1241 done.
1242 done.
1243 done.
1244 done.
1245 done.
1246 done.
1247 done.
1248 done.
1249 done.
1250 done.
1251 done.
1252 done.
1253 done.
1254 done.
1255 done.
1256 done.
1257 done.
1258 done.
1259 done.
1260 done.
1261 done.
1262 done.
1263 done.
1264 done.
1265 done.
1266 done.
1267 done.
1268 done.
1269 done.
1270 done.
1271 done.
1272 done.
1273 done.
1274 done.
1275 done.
1276 done.
1277 done.
1278 done.
1279 done.
1280 done.
1281 done.
1282 done.
1283 done.
1284 done.
1285 done.
1286 done.
1287 done.
1288 done.
1289 done.
1290 done.
1291 done.
1292 done.
1293 done.
1294 done.
1295 done.
1296 done.
1297 done.
1298 done.
1299 done.
1300 done.
1301 done.
1302 done.
1303 done.
1304 done.
1305 done.
1306 done.
1307 done.
1308 done.
1309 done.
1310 done.
1311 done.
1312 done.
1313 done.
1314 done.
1315 done.
1316 done.
1317 done.
1318 done.
1319 done.
1320 done.
1321 done.
1322 done.
1323 done.
1324 done.
1325 done.
1326 done.
1327 done.
1328 done.
1329 done.
1330 done.
1331 done.
1332 done.
1333 done.
1334 done.
1335 done.
1336 done.
1337 done.
1338 done.
1339 done.
1340 done.
1341 done.
1342 done.
1343 done.
1344 done.
1345 done.
1346 done.
1347 done.
1348 done.
1349 done.
1350 done.
1351 done.
1352 done.
1353 done.
1354 done.
1355 done.
1356 done.
1357 done.
1358 done.
1359 done.
1360 done.
1361 done.
1362 done.
1363 done.
1364 done.
1365 done.
1366 done.
1367 done.
1368 done.
1369 done.
1370 done.
1371 done.
1372 done.
1373 done.
1374 done.
1375 done.
1376 done.
1377 done.
1378 done.
1379 done.
1380 done.
1381 done.
1382 done.
1383 done.
1384 done.
1385 done.
1386 done.
1387 done.
1388 done.
1389 done.
1390 done.
1391 done.
1392 done.
1393 done.
1394 done.
1395 done.
1396 done.
1397 done.
1398 done.
1399 done.
1400 done.
1401 done.
1402 done.
1403 done.
1404 done.
1405 done.
1406 done.
1407 done.
1408 done.
1409 done.
1410 done.
1411 done.
1412 done.
1413 done.
1414 done.
1415 done.
1416 done.
1417 done.
1418 done.
1419 done.
1420 done.
1421 done.
1422 done.
1423 done.
1424 done.
1425 done.
1426 done.
1427 done.
1428 done.
1429 done.
1430 done.
1431 done.
1432 done.
1433 done.
1434 done.
1435 done.
1436 done.
1437 done.
1438 done.
1439 done.
1440 done.
1441 done.
1442 done.
1443 done.
1444 done.
1445 done.
1446 done.
1447 done.
1448 done.
1449 done.
1450 done.
1451 done.
1452 done.
1453 done.
1454 done.
1455 done.
1456 done.
1457 done.
1458 done.
1459 done.
1460 done.
1461 done.
1462 done.
1463 done.
1464 done.
1465 done.
1466 done.
1467 done.
1468 done.
1469 done.
1470 done.
1471 done.
1472 done.
1473 done.
1474 done.
1475 done.
1476 done.
1477 done.
1478 done.
1479 done.
1480 done.
1481 done.
1482 done.
1483 done.
1484 done.
1485 done.
1486 done.
1487 done.
1488 done.
1489 done.
1490 done.
1491 done.
1492 done.
1493 done.
1494 done.
1495 done.
1496 done.
1497 done.
1498 done.
1499 done.
1500 done.
1501 done.
1502 done.
1503 done.
1504 done.
1505 done.
1506 done.
1507 done.
1508 done.
1509 done.
1510 done.
1511 done.
1512 done.
1513 done.
1514 done.
1515 done.
1516 done.
1517 done.
1518 done.
1519 done.
1520 done.
1521 done.
1522 done.
1523 done.
1524 done.
1525 done.
1526 done.
1527 done.
1528 done.
1529 done.
1530 done.
1531 done.
1532 done.
1533 done.
1534 done.
1535 done.
1536 done.
1537 done.
1538 done.
1539 done.
1540 done.
1541 done.
1542 done.
1543 done.
1544 done.
1545 done.
1546 done.
1547 done.
1548 done.
1549 done.
1550 done.
1551 done.
1552 done.
1553 done.
1554 done.
1555 done.
1556 done.
1557 done.
1558 done.
1559 done.
1560 done.
1561 done.
1562 done.
1563 done.
1564 done.
1565 done.
1566 done.
1567 done.
1568 done.
1569 done.
1570 done.
1571 done.
1572 done.
1573 done.
1574 done.
1575 done.
1576 done.
1577 done.
1578 done.
1579 done.
1580 done.
1581 done.
1582 done.
1583 done.
1584 done.
1585 done.
1586 done.
1587 done.
1588 done.
1589 done.
1590 done.
1591 done.
1592 done.
1593 done.
1594 done.
1595 done.
1596 done.
1597 done.
1598 done.
1599 done.
1600 done.
1601 done.
1602 done.
1603 done.
1604 done.
1605 done.
1606 done.
1607 done.
1608 done.
1609 done.
1610 done.
1611 done.
1612 done.
1613 done.
1614 done.
1615 done.
1616 done.
1617 done.
1618 done.
1619 done.
1620 done.
1621 done.
1622 done.
1623 done.
1624 done.
1625 done.
1626 done.
1627 done.
1628 done.
1629 done.
1630 done.
1631 done.
1632 done.
1633 done.
1634 done.
1635 done.
1636 done.
1637 done.
1638 done.
1639 done.
1640 done.
1641 done.
1642 done.
1643 done.
1644 done.
1645 done.
1646 done.
1647 done.
1648 done.
1649 done.
1650 done.
1651 done.
1652 done.
1653 done.
1654 done.
1655 done.
1656 done.
1657 done.
1658 done.
1659 done.
1660 done.
1661 done.
1662 done.
1663 done.
1664 done.
1665 done.
1666 done.
1667 done.
1668 done.
1669 done.
1670 done.
1671 done.
1672 done.
1673 done.
1674 done.
1675 done.
1676 done.
1677 done.
1678 done.
1679 done.
1680 done.
1681 done.
1682 done.
1683 done.
1684 done.
1685 done.
1686 done.
1687 done.
1688 done.
1689 done.
1690 done.
1691 done.
1692 done.
1693 done.
1694 done.
1695 done.
1696 done.
1697 done.
1698 done.
1699 done.
1700 done.
1701 done.
1702 done.
1703 done.
1704 done.
1705 done.
1706 done.
1707 done.
1708 done.
1709 done.
1710 done.
1711 done.
1712 done.
1713 done.
1714 done.
1715 done.
1716 done.
1717 done.
1718 done.
1719 done.
1720 done.
1721 done.
1722 done.
1723 done.
1724 done.
1725 done.
1726 done.
1727 done.
1728 done.
1729 done.
1730 done.
1731 done.
1732 done.
1733 done.
1734 done.
1735 done.
1736 done.
1737 done.
1738 done.
1739 done.
1740 done.
1741 done.
1742 done.
1743 done.
1744 done.
1745 done.
1746 done.
1747 done.
1748 done.
1749 done.
1750 done.
1751 done.
1752 done.
1753 done.
1754 done.
1755 done.
1756 done.
1757 done.
1758 done.
1759 done.
1760 done.
1761 done.
1762 done.
1763 done.
1764 done.
1765 done.
1766 done.
1767 done.
1768 done.
1769 done.
1770 done.
1771 done.
1772 done.
1773 done.
1774 done.
1775 done.
1776 done.
1777 done.
1778 done.
1779 done.
1780 done.
1781 done.
1782 done.
1783 done.
1784 done.
1785 done.
1786 done.
1787 done.
1788 done.
1789 done.
1790 done.
1791 done.
1792 done.
1793 done.
1794 done.
1795 done.
1796 done.
1797 done.
1798 done.
1799 done.
1800 done.
1801 done.
1802 done.
1803 done.
1804 done.
1805 done.
1806 done.
1807 done.
1808 done.
1809 done.
1810 done.
1811 done.
1812 done.
1813 done.
1814 done.
1815 done.
1816 done.
1817 done.
1818 done.
1819 done.
1820 done.
1821 done.
1822 done.
1823 done.
1824 done.
1825 done.
1826 done.
1827 done.
1828 done.
1829 done.
1830 done.
1831 done.
1832 done.
1833 done.
1834 done.
1835 done.
1836 done.
1837 done.
1838 done.
1839 done.
1840 done.
1841 done.
1842 done.
1843 done.
1844 done.
1845 done.
1846 done.
1847 done.
1848 done.
1849 done.
1850 done.
1851 done.
1852 done.
1853 done.
1854 done.
1855 done.
1856 done.
1857 done.
1858 done.
1859 done.
1860 done.
1861 done.
1862 done.
1863 done.
1864 done.
1865 done.
1866 done.
1867 done.
1868 done.
1869 done.
1870 done.
1871 done.
1872 done.
1873 done.
1874 done.
1875 done.
1876 done.
1877 done.
1878 done.
1879 done.
1880 done.
1881 done.
1882 done.
1883 done.
1884 done.
1885 done.
1886 done.
1887 done.
1888 done.
1889 done.
1890 done.
1891 done.
1892 done.
1893 done.
1894 done.
1895 done.
1896 done.
1897 done.
1898 done.
1899 done.
1900 done.
1901 done.
1902 done.
1903 done.
1904 done.
1905 done.
1906 done.
1907 done.
1908 done.
1909 done.
1910 done.
1911 done.
1912 done.
1913 done.
1914 done.
1915 done.
1916 done.
1917 done.
1918 done.

In [95]:
data_llm=pd.DataFrame(dict_llm).T
data_llm.to_csv("/teamspace/studios/this_studio/NLP-Projects/LLM-for-IDS-log-analysis/Data/LLM_Data/data_v1.csv",index=False)

### Making the responses

In [25]:
import pandas as pd
import numpy as np

In [26]:
data_llm=pd.read_csv("/teamspace/studios/this_studio/NLP-Projects/LLM-for-IDS-log-analysis/Data/LLM_Data/data_v1.csv")

In [10]:
first=3435
end=3440
count=first
prompt=f"generate why the network traffic classifier decided on classifying each network traffic as normal or a type of attack, based on the information in the inputs especially the SHAP values, keep each explanation in one paragraph and use no bullet points and no titles or headers and also return to the line once not twice after each explanation. always begin the response with '{first}, The model classified this traffic as' and keep incrementing {first} until you reach {end-1}."
prompt=prompt+" return to the line only one time after generating each end of sentence token.\n"
for i in range(first,end) : 
    prompt=prompt+f"\n(input {count} : {data_llm.prompt.iloc[i]})"
    count+=1
print(prompt)

generate why the network traffic classifier decided on classifying each network traffic as normal or a type of attack, based on the information in the inputs especially the SHAP values, keep each explanation in one paragraph and use no bullet points and no titles or headers and also return to the line once not twice after each explanation. always begin the response with '3435, The model classified this traffic as' and keep incrementing 3435 until you reach 3439. return to the line only one time after generating each end of sentence token.

(input 3435 : Network Traffic :

Flow state flags: State ESTABLISHED
Transaction protocol : TCP
Source IP address : 192.168.100.3
Destination IP address : 192.168.100.149
Destination address type : Private

Transaction information :
-Total count of packets in transaction : 2.0
-Total number of bytes in transaction : 134.0
-Transaction State : RESET
-Record total duration : 0.0
-Average duration of aggregated records : 0.0
-Minimum duration of aggregated records : 0.0
-Destination-to-source packet count : 1.0
-Destination-to-source byte count : 60.0
-Total Number of packets per destination port : 105062.0
-Average rate per protocol per Destination IP : 6362.9
-Average rate per protocol per source port : 6535.95
-Number of packets grouped by state of flows and protocols per destination IP : 20322.0

Classifier Decision : Keylogging attack

SHAP Values that represent how much a particular feature influenced the final decision:
-SHAP Value for Source IP Address (192.168.100.3) : 3.680000066757202. (Feature value: 1.0)
-SHAP Value for Destination IP Address (192.168.100.149) : 1.5499999523162842. (Feature value: 1.0)
-SHAP Value for Total Number of packets per destination port : 1.4700000286102295. (Feature value: 105062.0)
-SHAP Value for Average rate per protocol per Destination IP : 1.0099999904632568. (Feature value: 6362.904746110092)
-SHAP Value for Total count of packets in transaction : 0.9700000286102295. (Feature value: 2.0)
-SHAP Value for Total number of bytes in transaction : 0.6200000047683716. (Feature value: 134.0)
-SHAP Value for Record total duration : 0.47999998927116394. (Feature value: 0.000153)
-SHAP Value for Average rate per protocol per source port : 0.4699999988079071. (Feature value: 6535.947754)
-SHAP Value for Destination-to-source byte count : -0.4000000059604645. (Feature value: 60.0)
-SHAP Value for Minimum duration of aggregated records : -0.2800000011920929. (Feature value: 0.000153))
(input 3436 : Network Traffic :

Flow state flags: State ESTABLISHED
Transaction protocol : TCP
Source IP address : 192.168.100.3
Destination IP address : 192.168.100.149
Destination address type : Private

Transaction information :
-Total count of packets in transaction : 2.0
-Total number of bytes in transaction : 134.0
-Transaction State : RESET
-Record total duration : 0.0
-Average duration of aggregated records : 0.0
-Minimum duration of aggregated records : 0.0
-Destination-to-source packet count : 1.0
-Destination-to-source byte count : 60.0
-Total Number of packets per destination port : 105062.0
-Average rate per protocol per Destination IP : 6362.9
-Average rate per protocol per source port : 4975.12
-Number of packets grouped by state of flows and protocols per destination IP : 20322.0

Classifier Decision : Keylogging attack

SHAP Values that represent how much a particular feature influenced the final decision:
-SHAP Value for Source IP Address (192.168.100.3) : 3.680000066757202. (Feature value: 1.0)
-SHAP Value for Destination IP Address (192.168.100.149) : 1.5499999523162842. (Feature value: 1.0)
-SHAP Value for Total Number of packets per destination port : 1.4700000286102295. (Feature value: 105062.0)
-SHAP Value for Average rate per protocol per source port : 1.100000023841858. (Feature value: 4975.124512)
-SHAP Value for Total count of packets in transaction : 1.0. (Feature value: 2.0)
-SHAP Value for Average rate per protocol per Destination IP : 0.949999988079071. (Feature value: 6362.904746110092)
-SHAP Value for Total number of bytes in transaction : 0.6800000071525574. (Feature value: 134.0)
-SHAP Value for Record total duration : 0.5. (Feature value: 0.000201)
-SHAP Value for Destination-to-source byte count : -0.44999998807907104. (Feature value: 60.0)
-SHAP Value for Minimum duration of aggregated records : -0.27000001072883606. (Feature value: 0.000201))
(input 3437 : Network Traffic :

Flow state flags: State ESTABLISHED
Transaction protocol : TCP
Source IP address : 192.168.100.3
Destination IP address : 192.168.100.149
Destination address type : Private

Transaction information :
-Total count of packets in transaction : 2.0
-Total number of bytes in transaction : 134.0
-Transaction State : RESET
-Record total duration : 0.0
-Average duration of aggregated records : 0.0
-Minimum duration of aggregated records : 0.0
-Destination-to-source packet count : 1.0
-Destination-to-source byte count : 60.0
-Total Number of packets per destination port : 105062.0
-Average rate per protocol per Destination IP : 6362.9
-Average rate per protocol per source port : 6578.95
-Number of packets grouped by state of flows and protocols per destination IP : 20322.0

Classifier Decision : Keylogging attack

SHAP Values that represent how much a particular feature influenced the final decision:
-SHAP Value for Source IP Address (192.168.100.3) : 3.680000066757202. (Feature value: 1.0)
-SHAP Value for Destination IP Address (192.168.100.149) : 1.5499999523162842. (Feature value: 1.0)
-SHAP Value for Total Number of packets per destination port : 1.4700000286102295. (Feature value: 105062.0)
-SHAP Value for Average rate per protocol per Destination IP : 1.0099999904632568. (Feature value: 6362.904746110092)
-SHAP Value for Total count of packets in transaction : 0.9700000286102295. (Feature value: 2.0)
-SHAP Value for Total number of bytes in transaction : 0.6200000047683716. (Feature value: 134.0)
-SHAP Value for Record total duration : 0.47999998927116394. (Feature value: 0.000152)
-SHAP Value for Average rate per protocol per source port : 0.4699999988079071. (Feature value: 6578.947754)
-SHAP Value for Destination-to-source byte count : -0.4000000059604645. (Feature value: 60.0)
-SHAP Value for Minimum duration of aggregated records : -0.2800000011920929. (Feature value: 0.000152))
(input 3438 : Network Traffic :

Flow state flags: State ESTABLISHED
Transaction protocol : TCP
Source IP address : 192.168.100.3
Destination IP address : 192.168.100.150
Destination address type : Private

Transaction information :
-Total count of packets in transaction : 2.0
-Total number of bytes in transaction : 134.0
-Transaction State : RESET
-Record total duration : 0.0
-Average duration of aggregated records : 0.0
-Minimum duration of aggregated records : 0.0
-Destination-to-source packet count : 1.0
-Destination-to-source byte count : 60.0
-Total Number of packets per destination port : 105062.0
-Average rate per protocol per Destination IP : 8102.63
-Average rate per protocol per source port : 6211.18
-Number of packets grouped by state of flows and protocols per destination IP : 1288.0

Classifier Decision : Keylogging attack

SHAP Values that represent how much a particular feature influenced the final decision:
-SHAP Value for Source IP Address (192.168.100.3) : 3.619999885559082. (Feature value: 1.0)
-SHAP Value for Destination IP Address (192.168.100.150) : 1.6200000047683716. (Feature value: 1.0)
-SHAP Value for Total Number of packets per destination port : 1.409999966621399. (Feature value: 105062.0)
-SHAP Value for Average rate per protocol per Destination IP : 1.0499999523162842. (Feature value: 8102.626606827804)
-SHAP Value for Total count of packets in transaction : 0.8899999856948853. (Feature value: 2.0)
-SHAP Value for Total number of bytes in transaction : 0.6100000143051147. (Feature value: 134.0)
-SHAP Value for Average rate per protocol per source port : 0.4300000071525574. (Feature value: 6211.180176)
-SHAP Value for Record total duration : 0.4300000071525574. (Feature value: 0.000161)
-SHAP Value for Destination-to-source byte count : -0.4300000071525574. (Feature value: 60.0)
-SHAP Value for Minimum duration of aggregated records : -0.27000001072883606. (Feature value: 0.000161))
(input 3439 : Network Traffic :

Flow state flags: State ESTABLISHED
Transaction protocol : TCP
Source IP address : 192.168.100.3
Destination IP address : 192.168.100.149
Destination address type : Private

Transaction information :
-Total count of packets in transaction : 2.0
-Total number of bytes in transaction : 134.0
-Transaction State : RESET
-Record total duration : 0.0
-Average duration of aggregated records : 0.0
-Minimum duration of aggregated records : 0.0
-Destination-to-source packet count : 1.0
-Destination-to-source byte count : 60.0
-Total Number of packets per destination port : 105062.0
-Average rate per protocol per Destination IP : 6362.9
-Average rate per protocol per source port : 6535.95
-Number of packets grouped by state of flows and protocols per destination IP : 20322.0

Classifier Decision : Keylogging attack

SHAP Values that represent how much a particular feature influenced the final decision:
-SHAP Value for Source IP Address (192.168.100.3) : 3.680000066757202. (Feature value: 1.0)
-SHAP Value for Destination IP Address (192.168.100.149) : 1.5499999523162842. (Feature value: 1.0)
-SHAP Value for Total Number of packets per destination port : 1.4700000286102295. (Feature value: 105062.0)
-SHAP Value for Average rate per protocol per Destination IP : 1.0099999904632568. (Feature value: 6362.904746110092)
-SHAP Value for Total count of packets in transaction : 0.9700000286102295. (Feature value: 2.0)
-SHAP Value for Total number of bytes in transaction : 0.6200000047683716. (Feature value: 134.0)
-SHAP Value for Record total duration : 0.47999998927116394. (Feature value: 0.000153)
-SHAP Value for Average rate per protocol per source port : 0.4699999988079071. (Feature value: 6535.947754)
-SHAP Value for Destination-to-source byte count : -0.4000000059604645. (Feature value: 60.0)
-SHAP Value for Minimum duration of aggregated records : -0.2800000011920929. (Feature value: 0.000153))

### Merging the prompts with the responses

In [27]:
prompts=pd.read_csv("/teamspace/studios/this_studio/NLP-Projects/LLM-for-IDS-log-analysis/Data/LLM_Data/prompts_final.csv")

In [28]:
len(prompts),len(data_llm)

(3538, 3538)

In [29]:
data_llm.head()

                                              prompt
0  Network Traffic :\n\nFlow state flags: State E...
1  Network Traffic :\n\nFlow state flags: State E...
2  Network Traffic :\n\nFlow state flags: State E...
3  Network Traffic :\n\nFlow state flags: State E...
4  Network Traffic :\n\nFlow state flags: State E...

In [31]:
prompts.columns=["id","response"]

In [33]:
data_llm=pd.concat([data_llm,prompts],axis=1)

In [35]:
data_llm=data_llm[["id","prompt","response"]]
data_llm.head()

,id,prompt,response
0,0,Network Traffic :\n\nFlow state flags: State E...,The model correctly classified this as a Servi...
1,1,Network Traffic :\n\nFlow state flags: State E...,The model correctly classified this as a DDoS ...
2,2,Network Traffic :\n\nFlow state flags: State E...,The model correctly classified this as a DoS a...
3,3,Network Traffic :\n\nFlow state flags: State E...,The model correctly classified this as a DoS a...
4,4,Network Traffic :\n\nFlow state flags: State E...,"The model classified this as Normal Traffic, r..."

In [36]:
data_llm.to_csv("/teamspace/studios/this_studio/NLP-Projects/LLM-for-IDS-log-analysis/Data/LLM_Data/full_llm_data.csv",index=False)

In [31]:
import pandas as pd
data_llm=pd.read_csv("/teamspace/studios/this_studio/NLP-Projects/LLM-for-IDS-log-analysis/Data/LLM_Data/full_llm_data.csv")
data_llm.head()

,id,prompt,response
0,0,Network Traffic :\n\nFlow state flags: State E...,The model correctly classified this as a Servi...
1,1,Network Traffic :\n\nFlow state flags: State E...,The model correctly classified this as a DDoS ...
2,2,Network Traffic :\n\nFlow state flags: State E...,The model correctly classified this as a DoS a...
3,3,Network Traffic :\n\nFlow state flags: State E...,The model correctly classified this as a DoS a...
4,4,Network Traffic :\n\nFlow state flags: State E...,"The model classified this as Normal Traffic, r..."

In [34]:
data_llm[data_llm.prompt.duplicated()]

,id,prompt,response
41,41,Network Traffic :\n\nFlow state flags: State E...,The classifier marked the traffic as normal ba...
58,58,Network Traffic :\n\nFlow state flags: State E...,The classifier identified the traffic as norma...
97,97,Network Traffic :\n\nFlow state flags: State E...,The classifier identified the network traffic ...
141,141,Network Traffic :\n\nFlow state flags: State E...,The classifier categorized the traffic as norm...
195,195,Network Traffic :\n\nFlow state flags: State E...,The classifier classified the network traffic ...
...,...,...,...
3530,3530,Network Traffic :\n\nFlow state flags: State E...,The model classified this traffic as a Keylogg...
3531,3531,Network Traffic :\n\nFlow state flags: State E...,The model classified this traffic as a Keylogg...
3533,3533,Network Traffic :\n\nFlow state flags: State E...,The model classified this traffic as a Keylogg...
3535,3535,Network Traffic :\n\nFlow state flags: State E...,The model classified this traffic as a keylogg...
3537,3537,Network Traffic :\n\nFlow state flags: State E...,The model classified this traffic as a keylogg...

In [ ]:
data_llm.